export const productData = {
  gasFirepit : [
    {
      id: 0,
      productImg: "./assets/img/product/gas-firepit-01.png",
      productName: "gas firepit",
      productMaterial: "Steel",
      productColor: "Balck",
      productSize: "H100 x D36 cm",
      productCode: "GF039354",
    },
    {
      id: 1,
      productImg: "./assets/img/product/gas-firepit-02.png",
      productName: "gas firepit",
      productMaterial: "Steel",
      productColor: "Balck",
      productSize: "H100 x D36 cm",
      productCode: "GF039354",
    },
    {
      id: 2,
      productImg: "./assets/img/product/gas-firepit-03.png",
      productName: "gas firepit",
      productMaterial: "Steel",
      productColor: "Balck",
      productSize: "H100 x D36 cm",
      productCode: "GF039354",
    },
    {
      id: 3,
      productImg: "./assets/img/product/gas-firepit-04.png",
      productName: "gas firepit",
      productMaterial: "Steel",
      productColor: "Balck",
      productSize: "H100 x D36 cm",
      productCode: "GF039354",
    },
    {
      id: 4,
      productImg: "./assets/img/product/gas-firepit-05.png",
      productName: "gas firepit",
      productMaterial: "Steel",
      productColor: "Balck",
      productSize: "H100 x D36 cm",
      productCode: "GF039354",
    },
    {
      id: 5,
      productImg: "./assets/img/product/gas-firepit-06.png",
      productName: "gas firepit",
      productMaterial: "Steel",
      productColor: "Balck",
      productSize: "H100 x D36 cm",
      productCode: "GF039354",
    },
  ],
  woodFirepit : [
    {
      id: 0,
      productImg: "./assets/img/product/wood-firepit-01.png",
      productName: "wood firepit",
      productMaterial: "Steel",
      productColor: "Balck",
      productSize: "H100 x D36 cm",
      productCode: "GF039354",
    },
    {
      id: 1,
      productImg: "./assets/img/product/wood-firepit-02.png",
      productName: "wood firepit",
      productMaterial: "Steel",
      productColor: "Balck",
      productSize: "H100 x D36 cm",
      productCode: "GF039354",
    },
    {
      id: 2,
      productImg: "./assets/img/product/wood-firepit-03.png",
      productName: "wood firepit",
      productMaterial: "Steel",
      productColor: "Balck",
      productSize: "H100 x D36 cm",
      productCode: "GF039354",
    },
    {
      id: 3,
      productImg: "./assets/img/product/wood-firepit-04.png",
      productName: "wood firepit",
      productMaterial: "Steel",
      productColor: "Balck",
      productSize: "H100 x D36 cm",
      productCode: "GF039354",
    },
    {
      id: 4,
      productImg: "./assets/img/product/wood-firepit-05.png",
      productName: "wood firepit",
      productMaterial: "Steel",
      productColor: "Balck",
      productSize: "H100 x D36 cm",
      productCode: "GF039354",
    },
    {
      id: 5,
      productImg: "./assets/img/product/wood-firepit-06.png",
      productName: "wood firepit",
      productMaterial: "Steel",
      productColor: "Balck",
      productSize: "H100 x D36 cm",
      productCode: "GF039354",
    },
  ],
  grillPizzaOven : [
    {
      id: 0,
      productImg: "./assets/img/product/grill-pizza-oven-01.png",
      productName: "grill&pizza oven",
      productMaterial: "Steel",
      productColor: "Balck",
      productSize: "H100 x D36 cm",
      productCode: "GF039354",
    },
    {
      id: 1,
      productImg: "./assets/img/product/grill-pizza-oven-02.png",
      productName: "grill&pizza oven",
      productMaterial: "Steel",
      productColor: "Balck",
      productSize: "H100 x D36 cm",
      productCode: "GF039354",
    },
    {
      id: 2,
      productImg: "./assets/img/product/grill-pizza-oven-03.png",
      productName: "grill&pizza oven",
      productMaterial: "Steel",
      productColor: "Balck",
      productSize: "H100 x D36 cm",
      productCode: "GF039354",
    },
    {
      id: 3,
      productImg: "./assets/img/product/grill-pizza-oven-04.png",
      productName: "grill&pizza oven",
      productMaterial: "Steel",
      productColor: "Balck",
      productSize: "H100 x D36 cm",
      productCode: "GF039354",
    },
  ],
  planter : [
    {
      id: 0,
      productImg: "./assets/img/product/planter-01.png",
      productName: "planter",
      productMaterial: "Steel",
      productColor: "Balck",
      productSize: "H100 x D36 cm",
      productCode: "GF039354",
    },
    {
      id: 1,
      productImg: "./assets/img/product/planter-02.png",
      productName: "planter",
      productMaterial: "Steel",
      productColor: "Balck",
      productSize: "H100 x D36 cm",
      productCode: "GF039354",
    },
    {
      id: 2,
      productImg: "./assets/img/product/planter-03.png",
      productName: "planter",
      productMaterial: "Steel",
      productColor: "Balck",
      productSize: "H100 x D36 cm",
      productCode: "GF039354",
    },
    {
      id: 3,
      productImg: "./assets/img/product/planter-04.png",
      productName: "planter",
      productMaterial: "Steel",
      productColor: "Balck",
      productSize: "H100 x D36 cm",
      productCode: "GF039354",
    },
    {
      id: 4,
      productImg: "./assets/img/product/planter-05.png",
      productName: "planter",
      productMaterial: "Steel",
      productColor: "Balck",
      productSize: "H100 x D36 cm",
      productCode: "GF039354",
    },
  ],
  gardenArch : [
    {
      id: 0,
      productImg: "./assets/img/product/garden-arch-01.png",
      productName: "garden arch",
      productMaterial: "Steel",
      productColor: "Balck",
      productSize: "H100 x D36 cm",
      productCode: "GF039354",
    },
    {
      id: 1,
      productImg: "./assets/img/product/garden-arch-02.png",
      productName: "garden arch",
      productMaterial: "Steel",
      productColor: "Balck",
      productSize: "H100 x D36 cm",
      productCode: "GF039354",
    },
    {
      id: 2,
      productImg: "./assets/img/product/garden-arch-03.png",
      productName: "garden arch",
      productMaterial: "Steel",
      productColor: "Balck",
      productSize: "H100 x D36 cm",
      productCode: "GF039354",
    },
  ],
  gardenDecoration : [
    {
      id: 0,
      productImg: "./assets/img/product/halloween-other-items-04.png",
      productName: "garden decoration",
      productMaterial: "Steel",
      productColor: "Balck",
      productSize: "H100 x D36 cm",
      productCode: "GF039354",
    },
    {
      id: 1,
      productImg: "./assets/img/product/halloween-other-items-05.png",
      productName: "garden decoration",
      productMaterial: "Steel",
      productColor: "Balck",
      productSize: "H100 x D36 cm",
      productCode: "GF039354",
    },
    {
      id: 2,
      productImg: "./assets/img/product/halloween-other-items-01.png",
      productName: "garden decoration",
      productMaterial: "Steel",
      productColor: "Balck",
      productSize: "H100 x D36 cm",
      productCode: "GF039354",
    },
    {
      id: 3,
      productImg: "./assets/img/product/halloween-other-items-02.png",
      productName: "garden decoration",
      productMaterial: "Steel",
      productColor: "Balck",
      productSize: "H100 x D36 cm",
      productCode: "GF039354",
    },
    {
      id: 4,
      productImg: "./assets/img/product/halloween-other-items-03.png",
      productName: "garden decoration",
      productMaterial: "Steel",
      productColor: "Balck",
      productSize: "H100 x D36 cm",
      productCode: "GF039354",
    },
    {
      id: 5,
      productImg: "./assets/img/product/garden-metal-stake-01.png",
      productName: "metal stake",
      productMaterial: "Steel",
      productColor: "Balck",
      productSize: "H100 x D36 cm",
      productCode: "GF039354",
    },
    {
      id: 6,
      productImg: "./assets/img/product/garden-metal-stake-02.png",
      productName: "metal stake",
      productMaterial: "Steel",
      productColor: "Balck",
      productSize: "H100 x D36 cm",
      productCode: "GF039354",
    },
    {
      id: 7,
      productImg: "./assets/img/product/garden-metal-wall-decoration-01.png",
      productName: "metal wall decoration",
      productMaterial: "Steel",
      productColor: "Balck",
      productSize: "H100 x D36 cm",
      productCode: "GF039354",
    },
    {
      id: 8,
      productImg: "./assets/img/product/garden-metal-wall-decoration-02.png",
      productName: "metal wall decoration",
      productMaterial: "Steel",
      productColor: "Balck",
      productSize: "H100 x D36 cm",
      productCode: "GF039354",
    },
    {
      id: 9,
      productImg: "./assets/img/product/garden-metal-wall-decoration-03.png",
      productName: "metal wall decoration",
      productMaterial: "Steel",
      productColor: "Balck",
      productSize: "H100 x D36 cm",
      productCode: "GF039354",
    },
    {
      id: 10,
      productImg: "./assets/img/product/flower-stand-01.png",
      productName: "flower stand",
      productMaterial: "Steel",
      productColor: "Balck",
      productSize: "H100 x D36 cm",
      productCode: "GF039354",
    },
    {
      id: 11,
      productImg: "./assets/img/product/flower-stand-02.png",
      productName: "flower stand",
      productMaterial: "Steel",
      productColor: "Balck",
      productSize: "H100 x D36 cm",
      productCode: "GF039354",
    },
    {
      id: 12,
      productImg: "./assets/img/product/flower-stand-03.png",
      productName: "flower stand",
      productMaterial: "Steel",
      productColor: "Balck",
      productSize: "H100 x D36 cm",
      productCode: "GF039354",
    },

  ],
};